### ISSUE TITLE
map shorthand - BaseNode#from - TypeError: this is not a constructor

### ISSUE THREAD

**Issue by haydenrou** [drborges/arbor#83]
When attempting to shorthand `map` over `BaseNode.from`, you receive the following error:
<img width="836" alt="Screenshot 2023-05-25 at 13 08 42" src="https://github.com/drborges/arbor/assets/21108297/57e5334f-45ab-4c94-9f9b-179cc116a4d4">

Occurs when:
`[{ uuid: "asd", text: "my text", completed: false }].map(BaseNode.from)`
Does not occur when:
`[{ uuid: "asd", text: "my text", completed: false }].map(item => BaseNode.from(item))`

An example of where I'm using this is in the persistance deserializer:
```
export const persistence = new LocalStorage<Todos>({
  key: "todoist.todos",
  debounceBy: 300,
  deserialize: (items) => {
    const todos = Object.values(items?.todos || {}).map(Todo.from)
    return Todos.from<Todos>({
      todos: new Repository(...todos)
    })
  },
})
```

**Comment by drborges** [comment]
Closing this since `BaseNode` has been removed in recent versions.
